version: '3.8'

services:
  airflow:
    build: .
    ports:
      - "8000:8000"
    environment:
      - AIRFLOW__API__PORT=8000
      - AIRFLOW__CORE__CONFIG_FILE=/app/config/webserver_config.yaml
      - AIRFLOW__WEBSERVER__AUTH_BACKEND=airflow.api.auth.backend.anonymous
      - AIRFLOW__WEBSERVER__SIMPLE_AUTH_MANAGER_ALL_ADMINS=True
    volumes:
      - ./dags:/app/dags
      - ./logs:/app/logs
      - ./plugins:/app/plugins
      - ./config:/app/config
    networks:
      - mlops-network
    command: >
      sh -c "
        uv run airflow db migrate &&
        uv run airflow standalone
      "

  mlflow:
    image: python:3.11-slim
    ports:
      - "8001:5000"
    volumes:
      - ./experiments:/app/experiments
      - ./models:/app/models
      - ./mlruns:/app/mlruns
    working_dir: /app
    command: >
      sh -c "
        pip install mlflow &&
        mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri ./mlruns
      "
    networks:
      - mlops-network

networks:
  mlops-network:
    driver: bridge

