[project]
name = "order-platform-msa-train-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "apache-airflow>=3.0.6",
    "dvc>=3.63.0",
    "mlflow>=3.3.2",
    "pytest>=8.4.1",
    "ruff>=0.12.11",
]
